default:
  tags:
    - docker

image:
  name: gradle:9-jdk25-alpine
  pull_policy: if-not-present

before_script:
  - set +o pipefail # stop pipes from failing entire pipeline
  - |
    cat <<EOF > gradle.properties
    systemProp.http.proxyHost=rtis-proxy-r01.uod.otago.ac.nz
    systemProp.http.proxyPort=3128
    systemProp.http.nonProxyHosts=altitude.otago.ac.nz|docker|172.17.0.*
    systemProp.https.proxyHost=rtis-proxy-r01.uod.otago.ac.nz
    systemProp.https.proxyPort=3128
    systemProp.https.nonProxyHosts=altitude.otago.ac.nz|docker|172.17.0.* 
    EOF
pages: 
  stage: build
  script:
    - echo "Attempting to generate Javadoc..."
    - gradle javadoc
    - echo "Publishing Javadoc..."
    - mkdir public
    - mv build/docs/javadoc/ public/
    - ls -R public | head
    - echo 'first ten public/ files listed'
  artifacts:
    paths:
    - public
  only:
  - main

unit-test-job:
  script:
  - echo "Attempting to run unit tests..."
  - gradle test